# Generated by Django 5.1.2 on 2024-10-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('object_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
