# Generated by Django 5.1.2 on 2024-10-16 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelobjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='type',
            new_name='object_type',
        ),
    ]
